### ISSUE TITLE
Downloadable log after import

### ISSUE THREAD

**Issue by netsensei** [PACKED-vzw/resolver#12]
Problem:

I'm importing a file with 5046 rows (1682 objects). The import is completed successfully but the stats tell me that there are only 1666 objects in the resolver.

There is no way to tell what happened to the 24 missing objects.

How to reproduce:

I've checked the import file and discovered that there are 24 rows that have duplicate PID's. The PID should be unique, however, sometimes an object can be published on multiple websites:

ex. 
PID: 100:
http://vlaamseprimitieven.vlaamsekunstcollectie.be/en/collection/the-story-of-saint-didacus-of-alcala-0
http://barokinvlaanderen.vlaamsekunstcollectie.be/en/collection/the-story-of-saint-didacus-of-alcala-9

However, it's possible that this not the only reason why on object wasn't imported.

Actual result:

On the surface, the importer fails to import all the rows in the file and fails to report why.

Expected result:

If you're importing a limited number of items, it's easy to spot duplicates. If you're importing 1682 objects, the resolver should give you a report of duplicate rows which were not imported.

**Comment by pieterdp** [comment]
I would say the silently merging multiple records with the same PID is "as designed". PID's are the unique identifiers, if they are the same, the program assumes the attached documents belong to the same object. I'll try whether we can support a logfile which lists where imported objects went (i.e. imported as object or merged with an existing one with the same PID).
