### ISSUE TITLE
Make 'Add entity' button available on the 'edit' entity form

### ISSUE THREAD

**Issue by netsensei** [PACKED-vzw/resolver#17]
Flow:
1. Go to resolver.be/resolver/entity
2. Click on 'Add entity'
3. Fill out the 'ID' and 'Title'
4. Click on 'Add' to add the entity
5. You will be taken to resolver/entity/OBJECT_ID

Now if you want to add a new entity, you have to:
1. Click on 'Entities'
2. Wait for the entire list to load (if you have 5.000 entries, this could take a while)
3. Pickup the previous flow at step 1.

Now imagine doing this for i.e. 15 entities.

**Comment by nvgeele** [comment]
The fix used to solve #7 makes loading the index page significantly faster, so is this button still necessary?

**Comment by netsensei** [comment]
Yes. This is a UX issue. Regardless of the load time of the list page, an editor has to perform extra clicks (not the shortest path to get there).
