### ISSUE TITLE
error change pasword

### ISSUE THREAD

**Issue by bert-packed** [PACKED-vzw/resolver#2]
Dag Bert,

Zoals beloofd hierbij een mailtje met de melding dat ik mijn paswoord
niet kan wijzigen via het menu Users. Wanneer ik dit probeer, krijg ik
de volgende melding:

Bad RequestCSRF token missing or incorrect.

Groeten,
Guenevere

**Comment by netsensei** [comment]
Bevestigd. Ik zie dezelfde fout wanneer ik de gebruikersnaam van 'admin' probeer te veranderen.

**Comment by pieterdp** [comment]
Probably has to do something with (in resolver/**init**.py):

```
import resolver.controllers

csrf = CsrfProtect()
csrf.init_app(app)

wsgi_app = RemoteUserMiddleware(app.wsgi_app)
```
