### ISSUE TITLE
Unicode import not succesful

### ISSUE THREAD

**Issue by pieterdp** [PACKED-vzw/resolver#20]
When importing a UTF-8-encoded (by PHP) CSV-file (https://drive.google.com/file/d/0B_yiyeb5zhbCTVdobHRhR3pTc2M/view?usp=sharing), the following error is returned:
" 'ascii' codec can't encode character u'\xe4' in position 1: ordinal not in range(128) "

**Comment by nvgeele** [comment]
Importing the provided file succeeds in 90e89889b31847c7de0c0ba7915529db8b6991a5
