### ISSUE TITLE
Bulk delete entries impossible

### ISSUE THREAD

**Issue by netsensei** [PACKED-vzw/resolver#27]
Version 1.5 introduced a change in importing entities.  Instead of clearing the entire database and importing all files, the import entails an incremental update.  

Existing records are updated and new records are added. However, there is no way to delete old records in bulk. You can only delete them manually via the interface.  

=> Deleting say 50 items in a list of 12.500 items becomes a chore since you have to filter one by one by PID.
=> There is no way to clear the entire database of all the records from the UI (use case: you made a serious mistake in your import and you need to start over)
- Suggestion 1: Add a "purge" button that allows you to purge the entire database.
- Suggestion 2: Add a form with a single text area element that allows you to input a list of PID's - delimited by newlines or breaks - that should be purged from the database.

**Comment by nvgeele** [comment]
Currently only the first suggestion will be implemented.
