### ISSUE TITLE
Debian package: location of initialise.py?

### ISSUE THREAD

**Issue by netsensei** [PACKED-vzw/resolver#28]
From the installation document:

> Execute the following command to create the default administrator user
> python /usr/share/resolver/bin/initialise.py

However, in the source code `initialise.py` is not in a bin/ folder but in the root folder of the project.

Why is there a difference?

**Comment by pieterdp** [comment]
According to the package, the initialise.py-file is where it should be. However, the source for the debian package is not developed in the master branch, but in the packaging branch. Perhaps that explains the confusion.

**Comment by netsensei** [comment]
So. Why is there a difference in project structure between the two branches? It's the same project / codebase? Doesn't the difference in folder structure complicate maintenance of the codebase (ie. porting bugs, etc.)?

**Comment by pieterdp** [comment]
The packaging branch tries to conform as close as possible to the [Debian File Hierarchy Standard](https://www.debian.org/doc/debian-policy/ch-opersys.html#s9.1), to ease possible integration in a Debian-compliant archive.
