### ISSUE TITLE
Version 1.5.0-1?

### ISSUE THREAD

**Issue by netsensei** [PACKED-vzw/resolver#31]
I noticed you just created a new version release with no documentation or release notes.

Per the semver (http://semver.org/) conventions: 

> A pre-release version indicates that the version is unstable and might not satisfy the intended compatibility requirements as denoted by its associated normal version. Examples: 1.0.0-alpha, 1.0.0-alpha.1, 1.0.0-0.3.7, 1.0.0-x.7.z.92.

Is this a pre-release? What is the rationele behind doing a pre-release at this point?

**Comment by pieterdp** [comment]
It's the debian release number (per http://www.fifi.org/doc/debian-policy/policy.html/ch-versions.html) and only exists in the debian-packaging branch
