### ISSUE TITLE
API: session cookie only?

### ISSUE THREAD

**Issue by netsensei** [PACKED-vzw/resolver#32]
The API contains several data-altering calls (Create/Update/Delete) over HTTP.  These calls need to be secured so that only authenticated / authorized users can access them. We don't want unauthorised users to alter the database.

The current implementation solely relies on session cookies to authenticate a user.  This is a security hazard as it leaves the application still wide open for XSRF (Cross Site Request Forgery) aanvallen.

See: https://miki.it/blog/2015/8/10/put-io-api-design-issues/

At this point, I could construct a HTML Form with a "PUT" on the "/api/entity/1234" HTTP url on another website. If I redirect a logged in user to that website, he would automagically alter PID 1234 as soon as (s)he submits the form.

Worth considering to crank up security by using something akin to https://gregorynicholas.github.io/flask-xsrf/

**Comment by pieterdp** [comment]
Authentication to the API is now via Basic Authentication.
