### ISSUE TITLE
Reset password form is not complete

### ISSUE THREAD

**Issue by netsensei** [PACKED-vzw/resolver#43]
The functionality of the 'reset password' form is not complete. Adding a user requires you to:
- Confirm your password.
- Restricts you password to a string >7 and < 64 characters.

The latter requirements is especially important. The current reset form allows you to set a password of < 7 characters. But those passwords are - apparently - invalid and won't let you log in:

How to reproduce:

1/ Create a new user with a password > 7 characters
2/ Reset the users password
3/ Use a password < 7 characters (ie. foobar)
4/ Logout
5/ Try to login => notice that you will be redirected to the signin form and that you don't get any warning or error messages.

**Comment by netsensei** [comment]
Okay. Noticed these in `forms.py`:

``` python
class SigninForm(Form):
    username = StringField('Username', [validators.required(),
                                        validators.Length(min=3, max=32)])
    password = PasswordField('Password', [validators.required(),
                                          validators.Length(min=7, max=64)])

class UserForm(SigninForm):
    confirm = PasswordField('Confirm', [validators.required()])
```

1/ Why would you put a restriction on what can be filled out in the signin form?  The signin form merely needs to assert if the username and password are equal to what is stored in the database. It shouldn't concern itself over the length of the input.

2/ UserForm is used for adding a user. It correctly registers validators for the 3 fields in the "add a new user" form on `/resolver/user`.  Given (1) I think you can squash the two classes together into one and appy the merged result on the "add a new user" form.

3/ The reset form only allows you to change the user password. So we will need a separate class for that.

Going to whip up a pull requests for these.

**Comment by netsensei** [comment]
Pieter,

Heb je dit getest vooraleer te committen?

**Comment by pieterdp** [comment]
Confirmed & closed.
