### ISSUE TITLE
Large imports break the import functionality

### ISSUE THREAD

**Issue by netsensei** [PACKED-vzw/resolver#5]
_Description_
Trying to import a large CSV file (6600 rows / 1.2Mb) breaks the importer

_Steps to reproduce_
1. Create a large import file via Open Refine
2. Navigate to the import interface
3. Import the file in the resolver

_Actual behavior_
- The browser redirects to a 502 or 504 error
- The file is only imported partly
- There are no log files allowing me to see if the error is triggered by a particular row in the CSV or because the process times out.

_Expected behaviour_
- A correct import and an redirect to a "success" landing page with a terse report of what happened.

_Proposed resolution_

Setting the --time-out flag on the gunicorn process to 240 seconds does some good: The CSV file gets imported entirely. However, I still see a 504 timeout message in the browser and no reports or log files.

Investigate other ways to import large CSV files.

**Comment by nvgeele** [comment]
Is the 504 reply generated by the Resolver or by the server in front of Gunicorn? In the latter case increasing the time-out time of both Gunicorn and the server might "fix" the issue somewhat.

**Comment by netsensei** [comment]
Hi,

nginx first threw me a 502. That led me to increase the time-out on the gunicorn process. 

Now the import ends up with a 504 error. But when I navigate back to the start/home page and take a look at the "stats" page, I see that the entire file was processed.

Matthias

**Comment by pieterdp** [comment]
The issue seems to be that the --timeout and --graceful-timout settings of the gunicorn process must be increased. A file of 15500 records needs a timeout of 286,66 seconds. We probably will need to rethink the import function to allow in-place updates and additions, thus negating the need for massive imports. I've increased the timeout in the example files.

**Comment by pieterdp** [comment]
Part of the reworking of the import module (#15)

**Comment by netsensei** [comment]
Pieter,
Alina,

Going to raise the priority on this one. 

I've just finished preparing the import file for MSK Gent.  The CSV file contains _12,825 rows_.  I've tried to importing this in a local test resolver on my laptop. I'm still required to raise the timeout limits because the file is just too large to be parsed within a single HTTP POST request.

At one point, trying to import the CSV file (2.8mb large) ended up in locking the MySQL database server requiring me to restart it. That shouldn't even happen at all.

The file contains: references to _8799_ entities or inventory numbers.  These are _all_ the relevant inventory numbers as registered in the collection management system of MSK as per the PACKED recommendations. 

We decided to refer the data/representation URLs to the VKC online catalogue which results in 4,026 entries.  Split out in an import CSV in Refine I end up with:
- 4,026 data entries
- 4,026 representation entries
- 4,773 blank entries that don't have published URL but still need to be imported for future use.

Importing such large numbers of data in the resolver is currently really tricky and error prone. 

The MSK is not the only museum with a dataset of that size.  Other medium/large museums trying to import their data in the resolver will face the same issues.

Matthias

**Comment by netsensei** [comment]
> "A file of 15500 records needs a timeout of 286,66 seconds."

1/
Timeout depends on available system resources.

I'm looking at less records but a timeout of 300 seconds was not enough. I tried importing in a resolver instance, installed on a vagrant box on my Macbook.

2/

> "We probably will need to rethink the import function to allow in-place updates and additions, thus negating the need for massive imports. "

I'm preparing a first time import. That's always going to be a "massive" import. 

I agree that it should be somehow possible to import smaller subsets of ie 100 or 1,000 records with updates to the data. Currently, the only way to do that is to make your changes and upload the entire dataset (15.000 records) again.

**Comment by pieterdp** [comment]
@netsensei Can you attach the file? We'll test it on the server.
