### ISSUE TITLE
Importing disabled URL's is impossible

### ISSUE THREAD

**Issue by netsensei** [PACKED-vzw/resolver#9]
Problem

I'm trying to import an object with 3 persistent URI's : 1 data URL + 2 representation URL's. The representation URL's should not be enabled in the resolver.  When a visitor tries to access them, they should see the note as defined in the "notes" column of the import file.

However, when trying to generate a "disabled" persistent URI via the import file, the resolver will still allow access to the referenced resource.

How to reproduce
1. Create a new import file
2. Add 1 object with 1 representation URL (jpg) that should be referenced.
3. Set the "enabled" column to "0" for the resource URL
4. Set the "notes" column to a custom note for the affected row
5. Import the file in a resolver instance
6. navigate to http://yourresolver/collection/work/representation/OBJECT_ID

Actual result

You are redirected to the resource by the resolver.

Expected result

You should see a page served by the resolver with the message as defined in the "notes" column of the import file.

**Comment by Alina-Packed** [comment]
Hi, I'm not sure that this will help but try leaving the cells in column 'enabled' empty instead of putting a '0' for URI's that should be disabled.

**Comment by netsensei** [comment]
Hi,

I've experimented a bit with this.

Apparently there are 2 ways to make disable a link:
- Leave the "enabled" row value empty
- Leave the "URL" row value empty

1/
I consider the latter to be some kind of a fallback. For instance: you want to make sure the resolver responds to a Persistent URI but you don't have the target link defined (yet).

=> Possible use case: A data publisher removes broken data/representation links but doesn't have new ones defined yet (ie. old website off line but new website is not on line yet)

I think creating disabled persistent URL's by leaving the URL value empty, is not the way to go. Later on, you need to update your import file in Refine with the representation/data URL's which can be an impractical affair. From a practical point of view, it's best to always have a target URL if you want to define a new persistent URI.

2/

The former way, leaving the enabled flag empty, is counter intuitive. I expect that you can disable a link by setting the value to 0.

**Comment by nvgeele** [comment]
A document will be enabled after import iff the value for the enabled row is 1.
